### ISSUE TITLE
The website cannot display the page?

### ISSUE THREAD

**Issue by squidmaeki** [Lukium/palworld-servertools#3]
![image](https://github.com/Lukium/palworld-servertools/assets/61579866/6663367d-6765-4424-9b45-8555a5dba420)

**Comment by Lukium** [comment]
What version of windows are you running?

Currently the UI is based on webview2, which I'm fairly confident is in Windows 10/11

**Comment by squidmaeki** [comment]
> What version of windows are you running?
> 
> Currently the UI is based on webview2, which I'm fairly confident is in Windows 10/11

![image](https://github.com/Lukium/palworld-servertools/assets/61579866/f49ce25a-fd98-4803-9daa-65e568f72ded)

**Comment by Lukium** [comment]
> > What version of windows are you running?
> > Currently the UI is based on webview2, which I'm fairly confident is in Windows 10/11
> 
> ![image](https://private-user-images.githubusercontent.com/61579866/303653954-f49ce25a-fd98-4803-9daa-65e568f72ded.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDc1MDc5MDcsIm5iZiI6MTcwNzUwNzYwNywicGF0aCI6Ii82MTU3OTg2Ni8zMDM2NTM5NTQtZjQ5Y2UyNWEtZmQ5OC00ODAzLTlkYWEtNjVlNTY4ZjcyZGVkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMDklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjA5VDE5NDAwN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTdiMzliMmEwNDZkNGI2MjZiZGMwMzE5MjMwZDEzNDc4ZWYyZTgwNGJmNjllMGNiOWFiODYzYzI2NzM5MjU1N2YmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.pU3iON5kCuwaIPFY6xjpCSdBvp7xDpQSdI8JGp7SVH8)

Would you mind giving this a try?
https://developer.microsoft.com/en-us/microsoft-edge/webview2/?form=MA13LH#download

**Comment by Lukium** [comment]
@BordZee on official Palworld Discord - #dedicated-server-help has now tested the suggested solution (installing webview2) on Windows Server 2022, and can now load the app. Marking the issue closed since a solution has been found and will consider auto-installing Webview2 (with user warning) if it's not found in the user system.
